### ISSUE TITLE
Searching for items does nothing

### ISSUE THREAD

**Issue by Alien-Kinger** [dangarfield/eve-jita-anywhere#2]
The search function in the browse tab doesn't seem to get the search info in (for instance PLEX, Phased Plasma M, etc)
Does work in the Bulk ordering!

**Comment by dangarfield** [comment]
Good spot. The rules here are:
- Must be 3 or more characters
- Must have less than 20 results

Plex = 21 results
Plasma = 67 results

I've set this equal less than 100, but I think I would like to improve this, but I think that 100 seems to work fairly well.
I'll close this for now, but will reopen if it's deemed as though there should be a better experience
