### ISSUE TITLE
Steps - Main page

### ISSUE THREAD

**Issue by Jer0men** [dangarfield/eve-jita-anywhere#5]
The sentences used in step 4 and step 6 don't make sense. 

"Sit back and relax; your goods will come to you"
![image](https://github.com/dangarfield/eve-jita-anywhere/assets/32482382/29e7312e-2950-4337-b6f1-3adbcf9bb79a)

"Play with game wherever you are"
![image](https://github.com/dangarfield/eve-jita-anywhere/assets/32482382/1e473e2d-cfcd-4949-bc08-b9a77e472945)

**Comment by dangarfield** [comment]
Any ideas for wording improvements?

**Comment by Jer0men** [comment]
"Sit back and relax; your goods will come to you" > "Complete jobs, get paid!"

I'm thinking something that says spend less time hauling, buying in game and more time flying/pewing.
"Play with game wherever you are" > "Affordable convenience"

**Comment by dangarfield** [comment]
Good suggestions. Deployed
